### ISSUE TITLE
standardiseGenotypes()

### ISSUE THREAD

**Issue by tanghaibao** [HannahVMeyer/PhenotypeSimulator#21]
@HannahVMeyer 

Thanks for the great package. Not sure if below is actually a bug or just an encoding confusion on my end:

Current code for `standardiseGenotypes()`

```R
standardiseGenotypes <- function(geno) {
    allele_freq <-  sapply(data.frame(geno),  getAlleleFrequencies)
    var_geno <- sqrt(2*allele_freq[1,]*allele_freq[2,])
    var_geno[var_geno == 0] <- 1
    geno_mean <- sweep(geno, 2, 2*allele_freq[1,], "-")
    geno_sd <- sweep(geno_mean, 2, var_geno, "/")
    return (geno_sd)
}
```
The math given was credited from here:
![image](https://user-images.githubusercontent.com/106987/69031842-df53b600-098f-11ea-836d-e6c8a74e6bb6.png)

While the formula matches the one in the GCTA reference, it seems that the formula requires that`geno` contain the dosage of __reference allele__, i.e. REF/REF => 2, REF/ALT => 1 etc.  However in `getAlleleFrequencies()` seems to suggest that the raw genotype matrix should be encoded with the dosage of __alternative allele__, based on how `p` was calculated:

```R
getAlleleFrequencies <- function(snp) {
    pp <- length(which(snp == 0))
    pq2 <- length(which(snp == 1))
    qq <- length(which(snp == 2))

    if ((pp + pq2 + qq != length(snp))) {
        stop ("SNP vector contains alleles not encoded as 0, 1 or 2")
    }
    p <- (2*pp +  pq2)/(2*length(snp))
    return(c(p, 1-p))
}
```

Would you please help confirm what the encodings of the genotype matrix are? 

Haibao

**Comment by alanaw1** [comment]
@HannahVMeyer Thanks for the package! I faced a similar issue to the one described here, and I think there is a quick fix. I'll describe the fix below, but first I ran an example to convince myself that the function was not demeaning the genotypes as described by Yang et al.

**_Experiment_**

First I simulate 100 genotypes with each genotype defined by 3 SNPs. Concretely, I'll get **X** with x[i,j] representing the number of copies of the reference allele. The seed is set to 2020 so that the example is reproducible.
  
```
# 1. Simulate 100 individual genotypes and 3 markers
set.seed(2020)
geno <- cbind(rbinom(100, 2, 0.3), rbinom(100, 2, 0.4),rbinom(100, 2, 0.5))
```

Because the matrix entries are defined in terms of reference allele counts, to obtain _estimates_ of the underlying reference allele frequencies, we have to compute the column means and divide them by 2: 

```
# 2. Compute estimates of underlying reference allele frequencies
allele_freq <- colMeans(geno) / 2
allele_freq
```

This produced `[1] 0.29 0.43 0.495` as the output, which is a good estimate of the true frequencies (0.3, 0.4 and 0.5) used in the simulation. Now, I run the first line in the body of `standardiseGenotypes`, which computes the allele frequencies and returns a 2 x P array. 

```
# 3. Compute estimates of underlying reference allele frequencies using package function
allele_freq_2 <-  sapply(data.frame(geno),  getAlleleFrequencies)
```  

According to the rest of the body of the `standardiseGenotypes` function, especially the line `p <- (2*pp +  pq2)/(2*length(snp))`, it seems to treat the matrix entries to be defined in terms of alternate allele counts. Indeed, in estimating the underlying reference allele frequency `p`, `pp` counts the number of zeros rather than twos, which is consistent with assuming the matrix entries to be defined in terms of alternate allele counts. So according to the way `standardiseGenotypes` is written as is, we should interpret the 2 x P array output as follows: the first row should represent estimates of underlying reference allele frequencies, while the second row should represent estimates of underlying alternate allele frequencies. So I checked the output.

```
# 4. Check output
allele_freq_2
```  

I got this:

```
       X1   X2    X3
[1,] 0.71 0.57 0.505
[2,] 0.29 0.43 0.495
```   

Notice that the order is flipped from what we expected it to be based on Code chunks 1 and  2.
 
**_How to fix_**

One quick fix to the code is to edit the following line in the body of the standardiseGenotypes function. Instead of `geno_mean <- sweep(geno, 2, 2*allele_freq[1,], "-")`, use `geno_mean <- sweep(geno, 2, 2*allele_freq[2,], "-")`. That way, the demeaning step of the standardization is performed correctly.  Everything else should work fine! 

I tried this myself and obtained zero means across the three SNPs. 

```
## A quick fix
# Define modified function
standardiseGenotypes_ <- function(geno) {
    allele_freq <-  sapply(data.frame(geno),  getAlleleFrequencies)
    var_geno <- sqrt(2*allele_freq[1,]*allele_freq[2,])
    var_geno[var_geno == 0] <- 1
    geno_mean <- sweep(geno, 2, 2*allele_freq[2,], "-")
    geno_sd <- sweep(geno_mean, 2, var_geno, "/")
    return (geno_sd)
}

# Apply modified function and check column means
colMeans(standardiseGenotypes_(geno))
```

Voilà: `[1] -1.332268e-16 -1.226796e-16  2.714842e-17`.

**Comment by HannahVMeyer** [comment]
Thanks for your comment, I will have a closer look.
At first glance, it seems to be a discrepancy between definitions of reference/alternative and major/minor alleles. The frequencies you simulated (similar to the defaults I use in `simulateGenotypes`) would be minor allele frequencies as they are less than 0.5. When I compute the allele frequencies, however, I choose the major alleles as the reference, and the minor as the alternative. I think, commonly in genome annotations, reference == major, although this might not hold for some of the variants, and certainly not across different ethnicities. However, in the simulation, without reference genome, choosing the major alleles as reference seemed sensible. 
Looking through these functions and help documentation, I can see that this is confusing.
I believe there is not actually a bug in the code, but I will investigate and get back to you. In any case, I will update the documentation.

**Comment by alanaw1** [comment]
Thanks for clarifying @HannahVMeyer. I agree that the major alleles are usually taken to be reference alleles in genome annotations. I still think that the function is reporting the standardised matrix erroneously, by which I mean that the issue is independent of the reference allele being major or minor. The consequence of genotype matrix standardisation is that the column means of the _N_ x _P_ standardised individual-by-SNP matrix, **W**, should be zero, up to numerical precision errors. This is a consequence of the equation that @tanghaibao attached above, which I expound upon in the screenshot below.

<img width="742" alt="Screen Shot 2020-06-29 at 1 23 41 PM" src="https://user-images.githubusercontent.com/29695123/86052510-f4a3bf00-ba0b-11ea-9f65-e2fbc20466b1.png">

(The sum of a nonempty set of numbers is zero, if and only if the arithmetic mean of the same set is also zero.)  

However, this is not the case even when I try to simulate genotype matrices with reference alleles being major alleles; consider the following reproducible example.

```
##  Experiment (29th June 2020)
# 1. Simulate 100 individual genotypes and 3 markers
set.seed(2020)
geno <- cbind(rbinom(100, 2, 0.8), rbinom(100, 2, 0.7),rbinom(100, 2, 0.6))

# 2. Compute estimates of underlying reference allele frequencies
allele_freq <- colMeans(geno) / 2
allele_freq
```
Output produced: `[1] 0.820 0.665 0.565`. 

```
# 3. Compute estimates of underlying reference allele frequencies using package function
allele_freq_2 <-  sapply(data.frame(geno),  getAlleleFrequencies)
```

Output produced: 
```
       X1    X2    X3
[1,] 0.18 0.335 0.435
[2,] 0.82 0.665 0.565
```

Now try the standardiseGenotypes function provided by the package.

```
# 4. Compute column means using standardiseGenotypes 
colMeans(standardiseGenotypes(geno))
```

Output produced: `[1] 2.3558726 0.9887710 0.3708425`. Notice the sums of entries across all individuals j of SNPs 1, 2 and 3 are not zero. (In fact, their sums would be 100 times that, ie, `[1] 235.58726  98.87710  37.08425`.)  

Now try standardiseGenotypes_, which is described in my previous post. 

```
## A quick fix
# Define modified function
standardiseGenotypes_ <- function(geno) {
  allele_freq <-  sapply(data.frame(geno),  getAlleleFrequencies)
  var_geno <- sqrt(2*allele_freq[1,]*allele_freq[2,])
  var_geno[var_geno == 0] <- 1
  geno_mean <- sweep(geno, 2, 2*allele_freq[2,], "-")
  geno_sd <- sweep(geno_mean, 2, var_geno, "/")
  return (geno_sd)
}

#  Compute column means again
colMeans(standardiseGenotypes_(geno))
```

Output produced: `[1] -2.353673e-16 -1.088019e-16  1.879052e-16`. Notice the sums of entries are now zero, up to numerical precision errors. 

I am sorry if I sound pedantic! I just hope to use PhenotypeSimulator without having to worry about small issues like this.

**Comment by HannahVMeyer** [comment]
Thank you for the detailed report, derivation and suggestions. I have fixed the function as suggested here and included additional tests for expected outcomes:

```r
standardiseGenotypes <- function(geno, impute=FALSE) {
    if (any(is.na(geno)) & !impute) {
        stop("Missing genotypes found and impute=FALSE, cannot standardise",
             "genotypes; remove missing genotypes or set impute=TRUE for mean",
             "imputation of genotypes")
    }
    if (any(is.na(geno)) & impute) {
        geno <- round(apply(as.matrix(geno), 2, Hmisc::impute, fun=mean))
    }
    allele_freq <-  sapply(data.frame(geno),  getAlleleFrequencies)
    var_geno <- sqrt(2*allele_freq[1,]*allele_freq[2,])
    var_geno[var_geno == 0] <- 1
    geno_mean <- sweep(geno, 2, 2*allele_freq[2,], "-")
    geno_sd <- sweep(geno_mean, 2, var_geno, "/")
    return (geno_sd)
}

test_that('standardiseGenotypes returns genotypes with mean 0 and sd 1', {
              geno <- cbind(rbinom(10000, 2, 0.3), rbinom(10000, 2, 0.4))
              geno_sd <- standardiseGenotypes(geno)
              expect_equal(colMeans(geno_sd), expected = c(0,0),
                           tolerance = 10e-4)
              expect_equal(apply(geno_sd, 2, sd), expected = c(1,1),
                           tolerance = 10e-3)
              
              expect_equal(dim(geno), dim(geno_sd))
          })
```

Thank you for your (non-pedantic!) contribution!

This is currently on the development branch.
Can you try to install the dev version via:
```r
library(devtools)
install_github("HannahVMeyer/PhenotypeSimulator", ref="dev" )
```

 If it solves your issue, I will merge with master and resubmit to CRAN.
